orbs:
  tutorials-check: maximilianone/tutorial-checker@1.0.1
version: 2.1
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/15f197634234d80a32fa
workflows:
  build:
    jobs:
      - tutorials-check/build-pull-request
